version: 0.2
# https://docs.aws.amazon.com/codepipeline/latest/userguide/ecs-cd-pipeline.html
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - java -version
  build:
    commands:
      - echo Build started on $(date)
      - mvn package
  post_build:
    commands:
      - rm target/original-*.jar
      - cp target/*.jar app_latest.jar
      - cp pipeline/codedeploy/appspec.yml .
      - cp app_latest.jar app_$GIT_COMMIT_ID.jar
artifacts:
  files:
    - revision.zip
    - app.jar
    - app_$GIT_COMMIT_ID.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
